# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip

stages:
  - test
  - run
  - deploy

before_script:
  - python3 -V

test:
  tags:
    - k300
  script:
  - tox # Use tox to run tests
  only:
  - master

run:
  tags:
    - k300
  script:
  - python3 setup.py bdist_wheel
  # run the command here
  artifacts:
    paths:
    - dist/*.whl
  only:
    - master

deploy:
  before_script:
    # Prepare for push
    - git remote set-url origin https://${GITHUB_USER}:${CI_PUSH_TOKEN}@github.com/onlogic/Pykarbon.git
    - git config --global user.email ${GITLAB_USER_EMAIL}
    - git config --global user.name ${GITLAB_USER_ID}
  script:
    - git remote -v
    - echo test completed
    #- git push -u origin master
  when: manual
  only:
    - master

#pages:
#  script:
#  - cd doc ; make html
#  - mv build/html/ ../public/
#  artifacts:
#    paths:
#    - public
#  only:
#  - master
